### ISSUE TITLE
Hanging streams

### ISSUE THREAD

**Issue by SnosMe** [fails-components/webtransport#77] opened 2022-09-27 21:33 UTC
In Chrome

```ts
const stream = await wt.createBidirectionalStream();
const writer = stream.writable.getWriter();
await writer.write(new Uint8Array([0x01, 0x02]));
await writer.close();
```

on server

```ts
    for await (const data of stream.readable) {
      console.log(data)
    }
    console.log('OK: reading finished')
```

It prints `Uint8Array(2) [ 1, 2 ]` but never reaches `OK: reading finished`,
so basically `.read()` Promise never resolves with `{ done: true }`

**Comment by martenrichter** [comment] 2022-09-27 21:49
Well, I never used `of stream.readable` to test the code. I always used  `getReader` and `getWriter` and but it seems that my test code did not test the done part there neither.
Can you please first check if for simple example node webstream implementation supports the of iterator.
Then I may check in the weekend, if I can incorporate it in the test code and potentially fix the implementation.

**Comment by SnosMe** [comment] 2022-09-27 22:02
It does https://nodejs.org/docs/latest-v16.x/api/webstreams.html#async-iteration

I obviously tested with getReader and while loop and got same results, but I think we can agree that we should move forward and use new laguage sugar 😄

**Comment by martenrichter** [comment] 2022-09-28 01:21
I may be able to look at it on sunday.
In the meantime, what does happen if you use an unidirectional stream. In the bidirectional case the readable and writable are connected and you might need to cancel also the other. I hope I got the current behaviour close to spec, but I still might have missed something.

**Comment by martenrichter** [comment] 2022-10-02 13:24
I have just tested it. You need also to close the second stream. Then it should work.

**Comment by davedoesdev** [comment] 2022-10-08 16:17
I can repro this too. What do the specs say? It seems counter intuitive to have to close the writable too before the readable gets end-of-stream.

**Comment by martenrichter** [comment] 2022-10-08 17:12
I tried to understand the specs here as far as I could, But I am really unsure.
I got some clues from the discussion here
https://bugs.chromium.org/p/chromium/issues/detail?id=1337606
But also the reaable and writable are somewhat connected.
So if you get an idea how it should be and how I can tell this the streams, I am always happy to be closer to the spec.

FIN received is handled ulitmatively in `onStreamNetworkFinish`in the `webtransport.js` , these are all ultimatively coming from `http3streamvisitor.cc` and its header via `informAboutStreamNetworkFinish`.

**Comment by davedoesdev** [comment] 2022-10-09 07:09
The cause is the `fin` never gets read when it arrives with no data. This changes the behaviour to why I _think_ is sensible, and makes readable streams end after the writer has closed them.

```diff
diff --git a/src/http3wtstreamvisitor.cc b/src/http3wtstreamvisitor.cc
index 4c83828..ded844f 100644
--- a/src/http3wtstreamvisitor.cc
+++ b/src/http3wtstreamvisitor.cc
@@ -70,19 +70,17 @@ namespace quic
     {
         if (pause_reading_)
             return; // back pressure folks!
-        // first figure out if we have readable data
+        // figure out readable data size
         size_t readable = stream_->ReadableBytes();
-        if (readable > 0)
-        {
-            // ok create a string obj to hold the data
-            std::string *data = new std::string();
-            data->resize(readable);
-            WebTransportStream::ReadResult result = stream_->Read(&(*data)[0], readable);
-            data->resize(result.bytes_read);
-            QUIC_DVLOG(1) << "Attempted reading on WebTransport bidirectional stream "
-                          << ", bytes read: " << result.bytes_read;
-            eventloop_->informAboutStreamRead(this, data, result.fin);
-        }
+        // create a string obj to hold the data
+        std::string *data = new std::string();
+        data->resize(readable);
+        WebTransportStream::ReadResult result = stream_->Read(&(*data)[0], readable);
+        data->resize(result.bytes_read);
+        QUIC_DVLOG(1) << "Attempted reading on WebTransport bidirectional stream "
+                      << ", bytes read: " << result.bytes_read
+                      << ", fin: " << result.fin;
+        eventloop_->informAboutStreamRead(this, data, result.fin);
     }
 
     void Http3WTStream::doCanWrite()
diff --git a/src/webtransport.js b/src/webtransport.js
index 53c63e6..7874239 100644
--- a/src/webtransport.js
+++ b/src/webtransport.js
@@ -173,7 +173,7 @@ class Http3WTStream {
   }
 
   onStreamRead(args) {
-    if (args.data && !this.readableclosed) {
+    if (args.data && args.data.length && !this.readableclosed) {
       // console.log('stream read received', args.data, Date.now())
       this.readableController.enqueue(args.data)
       if (this.readableController.desiredSize < 0) this.objint.stopReading()
```

**Comment by martenrichter** [comment] 2022-10-09 07:39
OK, that is helpful.
However, the tests are hanging (`npm test`)
I have to figure out , what the problem is.

**Comment by davedoesdev** [comment] 2022-10-09 08:05
With #83 and change from the issue, I got the tests to pass with the following changes:

```diff
diff --git a/test/testsuite.js b/test/testsuite.js
index 2952b9d..0395a0a 100644
--- a/test/testsuite.js
+++ b/test/testsuite.js
@@ -145,6 +145,7 @@ export async function echoTestsConnection(transport) {
     throw new Error('outgoing bidi stream test failed')
   }
   console.log('next close reader')
+  await reader.closed;
   try {
     await reader.cancel(0)
     console.log('All data has been read.')
@@ -195,6 +196,7 @@ export async function echoTestsConnection(transport) {
       console.error(`An error occurred: ${error}`)
       throw new Error('incoming bidi stream test failed')
     }
+    await readbd.closed;
     try {
       await readbd.cancel(0)
       console.log('All data has been read for incoming bidi stream.')
@@ -253,6 +255,7 @@ export async function echoTestsConnection(transport) {
     console.error(`An error occurred: ${error}`)
     throw new Error('incoming unidi stream test failed')
   }
+  await readud.closed;
   if (readud) {
     try {
       await readud.cancel(0)
```

Without the `await`s for the `closed`s I was getting an uncaught C++ exception (controller already closed). Probably something in `cancel` C++ implementation needs to handle the error there.

**Comment by martenrichter** [comment] 2022-10-09 08:08
But the `cancel` before the stream is closed is legal, as far as I understand it. 
So it should not hang..., that is what I have to figure out.

**Comment by davedoesdev** [comment] 2022-10-09 08:09
Yes, I'll look more into it.
The tests don't hang for me locally, they exit after 20s when the loop guardian does its job.

**Comment by martenrichter** [comment] 2022-10-09 08:11
Sure, but the loop guardian is only there to get the CI/CD jobs canceled. These tests protect the master branch.
I am looking into it in parallel.

**Comment by davedoesdev** [comment] 2022-10-09 08:15
Ah OK, I was assuming that exit always occurs due to loop guardian.
When I ran `why-is-node-running` to check what's keeping things from exiting, it was the loop guardian.

**Comment by davedoesdev** [comment] 2022-10-09 08:18
Btw, I think the issue with the `cancel` is that it's being called after the stream is closed (due to FIN fix- the stream gets closed when all data is read).
It's interesting that the JS exception handler doesn't get called. That may even be a bug in Node.

```
all bidi received, next close writer
All data has been sent.
next close reader
terminate called after throwing an instance of 'Napi::Error'
  what():  Invalid state: Controller is already closed
Aborted (core dumped)
```

That really should get caught by:

```js
  console.log('next close reader')
  try {
    await reader.cancel(0)
    console.log('All data has been read.')
  } catch (error) {
    console.error(`An error occurred: ${error}`)
    throw new Error('outgoing bidi stream test failed')
  }
```

**Comment by martenrichter** [comment] 2022-10-09 08:21
Be careful, there are multiple streams since both the server and client are there.
I also thought it was because it was already canceled, but this is not the point, it is the other stream.

**Comment by martenrichter** [comment] 2022-10-09 08:24
And yes it is always the loop guardian, but if the task hangs it is a failure of the test.

**Comment by davedoesdev** [comment] 2022-10-09 08:35
OK the `Controller is already closed` was my fault, this fixes that (need to check isn't already closed):

```
diff --git a/src/webtransport.js b/src/webtransport.js
index 53c63e6..4bda28e 100644
--- a/src/webtransport.js
+++ b/src/webtransport.js
@@ -173,12 +173,12 @@ class Http3WTStream {
   }
 
   onStreamRead(args) {
-    if (args.data && !this.readableclosed) {
+    if (args.data && args.data.length && !this.readableclosed) {
       // console.log('stream read received', args.data, Date.now())
       this.readableController.enqueue(args.data)
       if (this.readableController.desiredSize < 0) this.objint.stopReading()
     }
-    if (args.fin) {
+    if (args.fin && !this.readableclosed) {
       this.readableController.close()
       this.readableclosed = true
     }
```

Now I get a hanging test :)

**Comment by martenrichter** [comment] 2022-10-09 08:43
The `cancel` was unfortunately from another stream..,
Anyway while looking at the other problem I had to revert on c++ side the change, and then it is not hanging. 
So I do not think the problem is on the js side...

**Comment by davedoesdev** [comment] 2022-10-09 08:44
OK yes resolving the promise got the tests to pass (see updated patch below). I'm not sure if it's hanging or not, they do pass but it does wait at the end.

```diff
diff --git a/src/webtransport.js b/src/webtransport.js
index 53c63e6..c065ba7 100644
--- a/src/webtransport.js
+++ b/src/webtransport.js
@@ -173,14 +173,21 @@ class Http3WTStream {
   }
 
   onStreamRead(args) {
-    if (args.data && !this.readableclosed) {
+    if (args.data && args.data.length && !this.readableclosed) {
       // console.log('stream read received', args.data, Date.now())
       this.readableController.enqueue(args.data)
       if (this.readableController.desiredSize < 0) this.objint.stopReading()
     }
     if (args.fin) {
-      this.readableController.close()
-      this.readableclosed = true
+      if (this.cancelres) {
+        const res = this.cancelres
+        this.cancelres = null
+        res()
+      }
+      if (!this.readableclosed) {
+        this.readableController.close()
+        this.readableclosed = true
+      }
     }
   }
 
```

Test output:

```
> @fails-components/webtransport@0.0.6 test
> node test/test.js

load webtransport binary: ../build_linux_x64/Debug/webtransport.node
start generating self signed certificate
start Http3Server and startup echo tests
start GlobalEventLoop
createGlobalEventLoop
server started now wait 2 seconds
now startup client
wait for client to be ready
wait for session
got a newsession
server session is ready
install datagram echo
client is ready
TEST 1: start
incoming bidi stream Uint8Array(3) [ 65, 66, 67 ] 1665305021456
incoming bidi stream Uint8Array(3) [ 68, 69, 70 ] 1665305021458
all bidi received, next close writer
All data has been sent.
next close reader
All data has been read.
webtransport sending bidistream success
TEST 1: finish
TEST 2: start
got a bidistream
bidiReader finished piping
incom bd Uint8Array(3) [ 71, 72, 73 ] 1665305021462
incom bd Uint8Array(3) [ 74, 75, 76 ] 1665305021463
All data has been sent for incoming bidi stream.
All data has been read for incoming bidi stream.
TEST 2: finish
TEST 3: start
now unidirectional tests
got a unidistream
incom ud Uint8Array(3) [ 77, 78, 79 ] 1665305021467
incom ud Uint8Array(3) [ 80, 81, 82 ] 1665305021468
All data has been sent for incoming unidi stream.
All data has been read for incoming unidi stream.
TEST 3: finish
TEST 4: start
finally test datagrams
unidiReader finished piping
incom dg Uint8Array(3) [ 83, 84, 85 ] 1665305021471
incom dg Uint8Array(3) [ 86, 87, 88 ] 1665305021471
All data has been sent for datagram stream.
test datagrams finished
TEST 4: finish
start close stream tests
client test finished, now close the client but wait 2 seconds
client closes now wait 2 seconds
bidiReader terminated
unidiReader terminated
server session was closed 0
The HTTP/3 connection to  https://127.0.0.1:8080/echo closed gracefully.
now stop server
tests finished!
Server is gone
shutdown GlobalEventLoop
event loop exited
eventloop destroy called
global event loop gone, everything alright
```

**Comment by martenrichter** [comment] 2022-10-09 08:50
Interesting it does not work for me...., may be different timing, or did I overlook something

**Comment by martenrichter** [comment] 2022-10-09 08:51
And I should copy all changes...

**Comment by martenrichter** [comment] 2022-10-09 08:58
Works should go soon into master
https://github.com/fails-components/webtransport/pull/84/commits/59744e0d43156f66f02729cb61e01e1199e6604c
since it may change the behaviour I am wondering, if it is patch or minor.

**Comment by davedoesdev** [comment] 2022-10-09 09:04
At least a patch. No need for major version on 0.x.x is there?

**Comment by martenrichter** [comment] 2022-10-09 09:06
The question is, if changes behavior and may break something (semantic versioning), but probably not.

**Comment by davedoesdev** [comment] 2022-10-22 06:45
I can confirm this is fixed

**Closed** 2022-10-30 20:13 UTC
