### ISSUE TITLE
Request data on session object and respond method

### ISSUE THREAD

**Issue by achingbrain** [fails-components/webtransport#119] opened 2022-11-07 09:54 UTC
The pattern from `net.Server` in node core is to accept all requests on a given port, then pass the request with path info, etc to the js side and let js decide the status code, response body, etc.

This module [hard codes 200/404/400 responses](https://github.com/fails-components/webtransport/blob/master/src/http3serverbackend.cc#L60-L83) and doesn't pass any request info along which is a lot less flexible. and means we can't have things like query or url params, dynamic paths, etc.

How about following the same pattern as node core?  This way we can also simplify the js side a bit as there will only be a single session stream, and you won't have to know the paths ahead of time, nor will they need to be stored on the C++ side as well.

`Http2Stream` in node has a [.respond](https://nodejs.org/dist/latest-v18.x/docs/api/http2.html#http2streamrespondheaders-options) method, something similar could be used to send the initial response?  Something like:

```js
const session = await // get session

await session.ready()

if (session.path === '/valid-path') {
  session.respond({
    ':status': 200
  })
  
  // process session as normal, open streams, etc
} else {
  session.respond({
    ':status': 404
  })
  session.close()
}
```

Having the following available on the js session object would be incredibly useful, all taken from the http/http2 request objects in node core:

* [.headers](https://nodejs.org/dist/latest-v18.x/docs/api/http2.html#requestheaders)
* [.method](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestmethod)
* [.path](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestpath)
* [.host](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requesthost)
* [.protocol](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestprotocol)

**Comment by martenrichter** [comment] 2022-11-07 15:23
> The pattern from `net.Server` in node core is to accept all requests on a given port, then pass the request with path info, etc to the js side and let js decide the status code, response body, etc.
But this would mean passing multiple message back and forth. This does not work well here. The difference is node.js uses a single event loop and a single thread. The two event loops will give you bad performance with back and forth passing and it is a lot of work, which only pays off, if you want to handle normal http3 beside webtransport.



> This module [hard codes 200/404/400 responses](https://github.com/fails-components/webtransport/blob/master/src/http3serverbackend.cc#L60-L83) and doesn't pass any request info along which is a lot less flexible. and means we can't have things like query or url params, dynamic paths, etc.

Sure, it is directly taken from the examples, which are C++ only.

> How about following the same pattern as node core? This way we can also simplify the js side a bit as there will only be a single session stream, and you won't have to know the paths ahead of time, nor will they need to be stored on the C++ side as well.

But it will have bad performance because of the threads. The double storage is a must because of the two threads.



> How about following the same pattern as node core? This way we can also simplify the js side a bit as there will only be a single session stream, and you won't have to know the paths ahead of time, nor will they need to be stored on the C++ side as well.
> 
> `Http2Stream` in node has a [.respond](https://nodejs.org/dist/latest-v18.x/docs/api/http2.html#http2streamrespondheaders-options) method, something similar could be used to send the initial response? Something like:
> 
> ```js
> const session = await // get session
> 
> await session.ready()
> 
> if (session.path === '/valid-path') {
>   session.respond({
>     ':status': 200
>   })
>   
>   // process session as normal, open streams, etc
> } else {
>   session.respond({
>     ':status': 404
>   })
>   session.close()
> }
> ```
Well but I do not want to break the current interface. I have a lot of code already written and its adds complexity to the C++ side, which I will be unable to maintain in the long run.


> Having the following available on the js session object would be incredibly useful, all taken from the http/http2 request objects in node core:
> 
>     * [.headers](https://nodejs.org/dist/latest-v18.x/docs/api/http2.html#requestheaders)
> 
>     * [.method](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestmethod)
> 
>     * [.path](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestpath)
> 
>     * [.host](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requesthost)
> 
>     * [.protocol](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestprotocol)

The question will be, what is sent from the user agent for webtransport. Beside not wanting to have a callback between the threads you can pass it along with the session object.

**Comment by martenrichter** [comment] 2022-11-07 21:21
> Having the following available on the js session object would be incredibly useful, all taken from the http/http2 request objects in node core:
> 
> * [.headers](https://nodejs.org/dist/latest-v18.x/docs/api/http2.html#requestheaders)
This may be  use and present. But I think that there is no mechanism for passing e.g. auth token to the webtransport from the browsers. So it may be fairly limited.
> * [.method](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestmethod)
I think it does not make sense for webtransport, only if you want to handle normal http/3
> * [.path](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestpath)
Makes sense.
> * [.host](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requesthost)
This would make sense to identify and log the host. Blocking it, you should rather use white and black list on c++ side.
> * [.protocol](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#requestprotocol)
This is always http/3 ior?

**Comment by martenrichter** [comment] 2022-11-07 21:41
> How about following the same pattern as node core? This way we can also simplify the js side a bit as there will only be a single session stream, and you won't have to know the paths ahead of time, nor will they need to be stored on the C++ side as well.

But a single session stream also means that you can not apply backpressure separately.
I constructed the interface in this way, so that you can use separate handlers for different streams.
Also you can add streams later, if you wish later.

But what is the use case you have in mind? RegEx as paths?
Can you not just use one path and send the data you would like to encode in the first bidi or unidi stream's data.
That is the way I am passing auth tokens and also the resources, which the client wants to access. And if it is not correct I close the session. I found encoding them as BSONs pretty handy.

Also  invoking a dynamical check needs also extensive rewriting here
https://github.com/fails-components/webtransport/blob/3ac51bc51c2cc1bcd8f6ba4e9eb15d7c170b5658/src/http3serverstream.cc#L166
and this actually a part of libquiche I do not fully understand, so not an easy task on the c++ side.  The function you analysed is as all c++ code completely synchronous.

**Comment by martenrichter** [comment] 2022-11-07 21:51
Ok I have read
https://github.com/libp2p/specs/blob/master/webtransport/README.md 
so I see what you probably want. All is about the query parameter? (Does chrome allow this?).
What about setting a flag to a path, that parameters can be appended. Then only the text until the `?` is matched. Or we match in general only before the query and also pass the query on. This is rather easy.

**Comment by martenrichter** [comment] 2022-11-08 07:28
I have thought about it.
What about having the ability to also register a callback (maximum 1) instead a path, that gets called after the static paths are not matched?
In order to make it happen, I have to implement a JS promise-like promise in C++ (normal promises in C++ work differently), and return this instead and call then the resolve asynchronously.

**Comment by martenrichter** [comment] 2022-11-12 08:10
Ok here in this PR
https://github.com/fails-components/webtransport/pull/123
 is a first attempt to make the request stuff async, a first step towards inspecting headers.

**Comment by martenrichter** [comment] 2022-11-12 14:24
Ok, a push to the PR is coming and I will merge the PR.
JS side request handling is now possible.
I was sloppy with types, so the 'any' type is almost everywhere in the new files.
I thought a fast solution to the problem is better than taking time to learn types. I think, if this problem is solved, you might be happy to fix the types. (Easy for you and difficult for me)

**Comment by martenrichter** [comment] 2023-10-16 06:29
I will close this, as a mechanism for this was implemented long ago.

**Closed by martenrichter** 2023-10-16 06:29 UTC
